version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  listen_service_1:
    image: listen_service
    build:
      context: .
      dockerfile: Dockerfile.listenservice
    container_name: listen_service_1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ConnectionStrings__RedisConnection=redis:6379
    # ports:
    #   - "9008:9008"
    depends_on:
      - redis
    restart: unless-stopped

  listen_service_2:
    image: listen_service
    build:
      context: .
      dockerfile: Dockerfile.listenservice
    container_name: listen_service_2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ConnectionStrings__RedisConnection=redis:6379
    # ports:
    #   - "9009:9008"
    depends_on:
      - redis
    restart: unless-stopped

  jobs:
    image: jobs
    build:
      context: .
      dockerfile: Dockerfile.jobs
    container_name: jobs
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ConnectionStrings__RedisConnection=redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  telegram:
    image: telegram
    build:
      context: .
      dockerfile: Dockerfile.telegram
    container_name: telegram
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ConnectionStrings__RedisConnection=redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: